### ISSUE TITLE
Add shorthand version of expose meta data

### ISSUE THREAD

**Issue by gzmask** [kumarshantanu/dime#5]
Instead of having to do `(defn ^{:expose :foo} foo ...)`, can we just do `(defn ^expose foo ...) instead? Also defaulting the expose name to be same as function name.

**Comment by kumarshantanu** [comment]
I think `(defn ^:expose foo ...)` (`^:expose` rather than `^expose`) is already supported. In fact, if any of the arguments has an `:inject` tag then `:expose` tag is automatically inferred for `defn`.

**Comment by gzmask** [comment]
Nice! My bad not finding that out, hope this bit got documented soon.

**Comment by kumarshantanu** [comment]
Actually, this bit is sort of alluded to in this section: https://github.com/kumarshantanu/dime/blob/master/doc/intro.md#understanding-injection-annotations
